# Generated by Django 3.1.4 on 2020-12-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('recommend_day', models.IntegerField()),
            ],
        ),
    ]
